on:
  push:
    branches: main

jobs:
  job_id:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: "actions/checkout@v4"

      - uses: "google-github-actions/auth@v3"
        with:
          workload_identity_provider: "projects/605540746604/locations/global/workloadIdentityPools/pool2/providers/poolid"
          service_account: "github@insighta-test1.iam.gserviceaccount.com"

      - run: gcloud auth configure-docker --quiet

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: gcr.io/insighta-test1/hello-insighta:latest

      - id: "deploy"
        uses: "google-github-actions/deploy-cloudrun@v3"
        with:
          service: "insighta-cloud-run"
          image: "gcr.io/insighta-test1/hello-insighta:latest"

      - name: "Use output"
        run: 'curl "${{ steps.deploy.outputs.url }}"'
